# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_DAVINCI) += \
	da850-lcdk.dtb \
	da850-enbw-cmc.dtb \
	da850-evm.dtb \
	da850-lego-ev3.dtb \
	da850-lego-ev3-adafruit18.dtb \
	da850-lego-ev3-color.dtb \
	da850-lego-ev3-lms2012.dtb
